const Data = [
    { id:"1",
      image: require('../../assets/Images/img1.jpg'),
      price: "50$",
    },
    { id:"2",
      image: require('../../assets/Images/img2.jpg'),
      price: "60$",
    },
    { id:"3",
      image: require('../../assets/Images/img3.jpg'),
      price: "90$",
    },
    { id:"4",
      image: require('../../assets/Images/img4.jpg'),
      price: "100$",
    },
    { id:"5",
      image: require('../../assets/Images/img5.jpg'),
      price: "200$",
    },
    { id:"6",
    image: require('../../assets/Images/img6.jpg'),
    price: "150$",
  },
  { id:"7",
    image: require('../../assets/Images/img7.jpg'),
    price: "100$",
  },
  { id:"8",
    image: require('../../assets/Images/img8.jpg'),
    price: "80$",
  },
  { id:"9",
    image: require('../../assets/Images/img9.jpg'),
    price: "850$",
  },
  { id:"10",
    image: require('../../assets/Images/img10.jpg'),
    price: "90$",
  },
  ];
  
  
  export default Data;
  